# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{awsum}
  s.version = "0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Timberlake"]
  s.date = %q{2010-09-19}
  s.email = %q{andrew@andrewtimberlake.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "awsum.gemspec",
     "lib/awsum.rb",
     "lib/awsum/ec2.rb",
     "lib/awsum/ec2/address.rb",
     "lib/awsum/ec2/availability_zone.rb",
     "lib/awsum/ec2/image.rb",
     "lib/awsum/ec2/instance.rb",
     "lib/awsum/ec2/keypair.rb",
     "lib/awsum/ec2/parsers/address_parser.rb",
     "lib/awsum/ec2/parsers/availability_zone_parser.rb",
     "lib/awsum/ec2/parsers/image_parser.rb",
     "lib/awsum/ec2/parsers/instance_parser.rb",
     "lib/awsum/ec2/parsers/keypair_parser.rb",
     "lib/awsum/ec2/parsers/purchase_reserved_instances_offering_parser.rb",
     "lib/awsum/ec2/parsers/region_parser.rb",
     "lib/awsum/ec2/parsers/register_image_parser.rb",
     "lib/awsum/ec2/parsers/reserved_instance_parser.rb",
     "lib/awsum/ec2/parsers/reserved_instances_offering_parser.rb",
     "lib/awsum/ec2/parsers/security_group_parser.rb",
     "lib/awsum/ec2/parsers/snapshot_parser.rb",
     "lib/awsum/ec2/parsers/volume_parser.rb",
     "lib/awsum/ec2/region.rb",
     "lib/awsum/ec2/reserved_instance.rb",
     "lib/awsum/ec2/reserved_instances_offering.rb",
     "lib/awsum/ec2/security_group.rb",
     "lib/awsum/ec2/snapshot.rb",
     "lib/awsum/ec2/volume.rb",
     "lib/awsum/error.rb",
     "lib/awsum/net_fix.rb",
     "lib/awsum/parser.rb",
     "lib/awsum/requestable.rb",
     "lib/awsum/s3.rb",
     "lib/awsum/s3/bucket.rb",
     "lib/awsum/s3/headers.rb",
     "lib/awsum/s3/object.rb",
     "lib/awsum/s3/parsers/bucket_parser.rb",
     "lib/awsum/support.rb",
     "spec/fixtures/ec2/addresses.xml",
     "spec/fixtures/ec2/allocate_address.xml",
     "spec/fixtures/ec2/associate_address.xml",
     "spec/fixtures/ec2/attach_volume.xml",
     "spec/fixtures/ec2/authorize_ip_access.xml",
     "spec/fixtures/ec2/authorize_owner_group_access.xml",
     "spec/fixtures/ec2/authorize_owner_group_access_error.xml",
     "spec/fixtures/ec2/availability_zones.xml",
     "spec/fixtures/ec2/available_volume.xml",
     "spec/fixtures/ec2/create_key_pair.xml",
     "spec/fixtures/ec2/create_security_group.xml",
     "spec/fixtures/ec2/create_snapshot.xml",
     "spec/fixtures/ec2/create_volume.xml",
     "spec/fixtures/ec2/delete_key_pair.xml",
     "spec/fixtures/ec2/delete_security_group.xml",
     "spec/fixtures/ec2/delete_snapshot.xml",
     "spec/fixtures/ec2/delete_volume.xml",
     "spec/fixtures/ec2/deregister_image.xml",
     "spec/fixtures/ec2/detach_volume.xml",
     "spec/fixtures/ec2/disassociate_address.xml",
     "spec/fixtures/ec2/image.xml",
     "spec/fixtures/ec2/images.xml",
     "spec/fixtures/ec2/instance.xml",
     "spec/fixtures/ec2/instances.xml",
     "spec/fixtures/ec2/internal_error.xml",
     "spec/fixtures/ec2/invalid_amiid_error.xml",
     "spec/fixtures/ec2/invalid_request_error.xml",
     "spec/fixtures/ec2/key_pairs.xml",
     "spec/fixtures/ec2/purchase_reserved_instances_offering.xml",
     "spec/fixtures/ec2/purchase_reserved_instances_offerings.xml",
     "spec/fixtures/ec2/regions.xml",
     "spec/fixtures/ec2/register_image.xml",
     "spec/fixtures/ec2/release_address.xml",
     "spec/fixtures/ec2/reserved_instances.xml",
     "spec/fixtures/ec2/reserved_instances_offering.xml",
     "spec/fixtures/ec2/reserved_instances_offerings.xml",
     "spec/fixtures/ec2/revoke_ip_access.xml",
     "spec/fixtures/ec2/revoke_owner_group_access.xml",
     "spec/fixtures/ec2/run_instances.xml",
     "spec/fixtures/ec2/security_groups.xml",
     "spec/fixtures/ec2/snapshots.xml",
     "spec/fixtures/ec2/terminate_instances.xml",
     "spec/fixtures/ec2/unassociated_address.xml",
     "spec/fixtures/ec2/volumes.xml",
     "spec/fixtures/errors/invalid_parameter_value.xml",
     "spec/fixtures/s3/buckets.xml",
     "spec/fixtures/s3/copy_failure.xml",
     "spec/fixtures/s3/invalid_request_signature.xml",
     "spec/fixtures/s3/keys.xml",
     "spec/lib/awsum/ec2/address_spec.rb",
     "spec/lib/awsum/ec2/availability_zones_spec.rb",
     "spec/lib/awsum/ec2/image_spec.rb",
     "spec/lib/awsum/ec2/instance_spec.rb",
     "spec/lib/awsum/ec2/keypair_spec.rb",
     "spec/lib/awsum/ec2/parsers/address_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/availability_zone_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/image_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/instance_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/keypair_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/purchase_reserved_instances_offering_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/region_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/register_image_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/reserved_instance_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/reserved_instances_offering_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/security_group_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/snapshot_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/volume_parser_spec.rb",
     "spec/lib/awsum/ec2/region_spec.rb",
     "spec/lib/awsum/ec2/reserved_instance_spec.rb",
     "spec/lib/awsum/ec2/reserved_instances_offering_spec.rb",
     "spec/lib/awsum/ec2/security_group_spec.rb",
     "spec/lib/awsum/ec2/snapshots_spec.rb",
     "spec/lib/awsum/ec2/volume_spec.rb",
     "spec/lib/awsum/ec2_spec.rb",
     "spec/lib/awsum/error_spec.rb",
     "spec/lib/awsum/requestable_spec.rb",
     "spec/lib/awsum/s3/bucket_spec.rb",
     "spec/lib/awsum/s3/object_spec.rb",
     "spec/lib/awsum/s3/parsers/bucket_parser_spec.rb",
     "spec/lib/awsum/s3/parsers/object_parser_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://andrewtimberlake.com/projects/awsum}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library for working with Amazon Web Services in the most natural rubyish way}
  s.test_files = [
    "spec/lib/awsum/s3/parsers/object_parser_spec.rb",
     "spec/lib/awsum/s3/parsers/bucket_parser_spec.rb",
     "spec/lib/awsum/s3/object_spec.rb",
     "spec/lib/awsum/s3/bucket_spec.rb",
     "spec/lib/awsum/ec2/reserved_instance_spec.rb",
     "spec/lib/awsum/ec2/region_spec.rb",
     "spec/lib/awsum/ec2/availability_zones_spec.rb",
     "spec/lib/awsum/ec2/parsers/register_image_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/security_group_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/image_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/snapshot_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/region_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/availability_zone_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/reserved_instance_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/address_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/purchase_reserved_instances_offering_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/volume_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/reserved_instances_offering_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/keypair_parser_spec.rb",
     "spec/lib/awsum/ec2/parsers/instance_parser_spec.rb",
     "spec/lib/awsum/ec2/image_spec.rb",
     "spec/lib/awsum/ec2/address_spec.rb",
     "spec/lib/awsum/ec2/keypair_spec.rb",
     "spec/lib/awsum/ec2/snapshots_spec.rb",
     "spec/lib/awsum/ec2/volume_spec.rb",
     "spec/lib/awsum/ec2/instance_spec.rb",
     "spec/lib/awsum/ec2/security_group_spec.rb",
     "spec/lib/awsum/ec2/reserved_instances_offering_spec.rb",
     "spec/lib/awsum/ec2_spec.rb",
     "spec/lib/awsum/error_spec.rb",
     "spec/lib/awsum/requestable_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.22"])
  end
end

